# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [2]:
import numpy as np

2. Create a null vector of size 10 

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a vector with values ranging from 10 to 49

In [10]:
find = np.arange(10,50)
print(find)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


4. Find the shape of previous array in question 3

In [11]:
find.shape

(40,)

5. Print the type of the previous array in question 3

In [13]:
find.dtype

dtype('int32')

6. Print the numpy version and the configuration


In [21]:
print("Version = ",np.__version__)
print("Config",np.show_config())

Version =  1.19.2
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/BEATZ/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/BEATZ/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/BEATZ/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/BEATZ/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/BEATZ/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/BEATZ/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/BEATZ/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/BEATZ/anaconda3\\Library\\include']
Config None


7. Print the dimension of the array in question 3


In [22]:
find.ndim

1

8. Create a boolean array with all the True values

In [27]:
find.astype(bool)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True])

9. Create a two dimensional array




In [28]:
np.random.randn(10,20)

array([[ 1.48197204e+00,  1.29079984e+00,  2.27555951e+00,
        -3.55185138e-01, -1.07537090e-01, -6.63789174e-01,
        -8.80662619e-01,  1.10715406e+00,  1.39515391e+00,
         8.65466375e-01, -1.29167230e+00, -1.22981728e+00,
         2.80431019e-02, -1.17019865e+00,  1.37979638e+00,
        -3.47933154e-02,  4.73279433e-01,  9.43115137e-01,
        -7.16446876e-01, -2.04241019e-01],
       [ 5.76813803e-01, -2.91526492e-01,  4.39906749e-01,
         2.01083558e-01,  1.86198223e+00,  2.32716248e+00,
        -7.02328341e-02, -6.93556624e-01, -1.28228407e-02,
        -2.60092489e-01, -2.52809700e-01, -5.57621254e-01,
         1.07743596e+00,  2.50736179e+00, -8.51658429e-02,
         1.31554095e-02, -1.26705566e-01,  3.25010221e-01,
         1.60105833e-01, -2.01545410e-01],
       [-1.91136412e-01, -1.63769414e+00, -1.56461881e-03,
        -8.84584725e-01, -1.93575551e+00,  8.48845184e-01,
        -1.26338003e+00,  8.66130956e-01,  6.01656028e-01,
        -3.56049842e-01,  1.6

10. Create a three dimensional array



In [29]:
np.random.randn(2,3,4)

array([[[-1.07686633, -0.83901156,  0.85354481, -0.78957743],
        [ 0.40684277, -0.53853749,  0.47729366,  0.58404525],
        [ 0.78025941, -0.70554206, -0.39711828,  1.17657885]],

       [[ 0.04130948, -1.59729424,  0.08053387,  0.29833397],
        [-1.28252764,  0.07216382,  1.11546748,  0.87037217],
        [-0.11144786, -0.57043168,  0.31574818,  0.39035103]]])

Difficulty Level **Easy**

In [38]:
find[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [43]:
arr = np.zeros(10)
arr[4] = 1
arr

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

13. Create a 3x3 identity matrix

In [48]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [51]:
arr.astype('float')

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [53]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],

           [7., 2., 12.]])
arr3 = arr1 * arr2
arr3

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [59]:
arr4 = arr1,arr2
np.array(arr4)

array([[[ 1.,  2.,  3.],
        [ 4.,  5.,  6.]],

       [[ 0.,  4.,  1.],
        [ 7.,  2., 12.]]])

17. Extract all odd numbers from arr with values(0-9)

In [76]:
od = np.arange(10)
od[od%2 == 1]

array([1, 3, 5, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [74]:
od = np.arange(10)
od[od % 2 == 1] = -1
od

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [79]:
arr5 = np.arange(10)
arr5[4:8] = 12
arr5

array([ 0,  1,  2,  3, 12, 12, 12, 12,  8,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [103]:
x = np.ones(16).reshape(4,4)
x[1,1:3] = 0
x[2,1:3] = 0
x

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [105]:
arr2d = np.array([[1, 2, 3],

            [4, 5, 6], 

            [7, 8, 9]])

arr2d[1,1] = 12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [106]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0,0] = 64
arr3d

array([[[64, 64, 64],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [109]:
a2d = np.arange(9).reshape(3,3)
a2d[0]

array([0, 1, 2])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [111]:
a2d[1,1]

4

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [114]:
st = a2d[0,2]
nd = a2d[1,2]
rd = st,nd
rd

(2, 5)

26. Create a 10x10 array with random values and find the minimum and maximum values

In [122]:
values = np.random.randn(100).reshape(10,10)
print(values)
maxi = values.max()
mini =values.min()
print('maximum Value is =',maxi ,'and minimum value =',mini)

[[ 0.38088852  0.33565378 -0.21291282  0.85973172 -1.02854231 -0.58408881
   0.08887133 -2.97692713  1.42129312  0.56931362]
 [-1.26743184  1.968507    0.13287567 -0.71811752  0.812082   -0.24082228
   2.18910264 -0.73641263 -1.2239951   1.0537065 ]
 [ 0.92696103 -1.25461589 -0.72432794  0.33747214 -0.02609992 -0.19264327
   0.57517934 -0.93371608 -0.45446268 -1.05303296]
 [ 0.7562005   1.38303271 -0.25448621  0.04850675  0.29051608  0.2267439
  -2.01958552 -1.5463902  -0.39517607  2.06461135]
 [ 1.37958815 -0.44777459 -0.04761352  0.32085987  0.30690851  1.5236081
  -1.00415067  2.01113662 -0.33255965 -0.5202074 ]
 [ 1.88006514  0.54256019 -1.99652648  0.58275694 -0.36204448 -0.11318461
   0.73391257  0.12204406 -0.59889238  0.65615234]
 [ 1.02043694  1.53273218  0.51176466 -1.129442   -0.53648641  1.35678513
  -0.30550433 -0.85190821  0.30144186 -0.03706748]
 [-0.27671508 -0.07687459  0.46890661 -1.28167522  0.07025919 -1.47875478
  -0.36302434 -0.17009683 -1.21823718  1.24554498]
 [

In [138]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
com = np.intersect1d(a,b)
com

array([2, 4])

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [244]:
np.searchsorted(a , np.intersect1d(a,b))

array([4], dtype=int64)

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [249]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
print(data[names != 'Will'])
# data

[[ 0.04660894  0.70447561  0.95047201 -0.67343315]
 [ 1.17282468  0.93896355  0.13053486  0.93059411]
 [-1.19434598 -0.62794934  1.07239699  0.69336964]
 [ 0.19526864 -1.21305816  0.22242933  1.37139337]
 [-0.49950165  0.41682859 -0.31749106  1.07810331]]


30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [250]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
print(data[names == 'Bob'])

[[ 0.79876726 -1.10731482  0.52847952  2.09280319]
 [ 0.97666246  0.12603129  0.69461259  0.78424422]]


Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [142]:
a = np.arange(16)
b = a[a != 0 ]
c = b.reshape(5,3)
c

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [180]:
a = np.arange(17)
b = a[a != 0 ]
c = b.reshape(2,2,4)
c

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

33. Swap axes of the array you created in Question 32

In [187]:
c.swapaxes(2,0)

array([[[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]],

       [[ 4, 12],
        [ 8, 16]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [208]:
s = np.array([0,1,2,3,4,5,6,7,8,9])
sq =np.sqrt(s)
res = sq[ sq > 0.5]
rep = 

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        ])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [242]:
y = np.arange(12).reshape(3,4)
z1 = np.max(y[0])
z2 = np.max(y[1])
z3 = np.max(y[2])
print(z1)
print(z2)
print(z3)

3
7
11


36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [227]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
res = np.unique(names)
res

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [221]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
diff = np.setdiff1d(a,b)
diff

array([1, 2, 3, 4])

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [216]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([[10,10,10]])
sampleArray[2] = newColumn
sampleArray

array([[34, 43, 73],
       [82, 22, 12],
       [10, 10, 10]])

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [214]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])
prod = np.dot(x,y)
prod

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [213]:
mat = np.arange(20).reshape(4,5)
matrix = np.cumsum(mat)
matrix


array([  0,   1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,
        91, 105, 120, 136, 153, 171, 190], dtype=int32)